/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as BundleRouteImport } from './routes/bundle'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as FeesRouteImport } from './routes/fees'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as YouRouteImport } from './routes/you'
import { Route as ListingsIdRouteImport } from './routes/listings.$id'
import { Route as ListingsNewRouteImport } from './routes/listings.new'
import { Route as PickupIdRouteImport } from './routes/pickup.$id'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesIdRouteImport } from './routes/sales.$id'
import { Route as SalesHowRouteImport } from './routes/sales.how'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BundleRoute = BundleRouteImport.update({
  id: '/bundle',
  path: '/bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesRoute = FeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsNewRoute = ListingsNewRouteImport.update({
  id: '/listings/new',
  path: '/listings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupIdRoute = PickupIdRouteImport.update({
  id: '/pickup/$id',
  path: '/pickup/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIdRoute = SalesIdRouteImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesHowRoute = SalesHowRouteImport.update({
  id: '/sales/how',
  path: '/sales/how',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/bundle': typeof BundleRoute
  '/corporate': typeof CorporateRoute
  '/desk': typeof DeskRoute
  '/fees': typeof FeesRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/records': typeof RecordsRoute
  '/sell': typeof SellRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/you': typeof YouRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/pickup/$id': typeof PickupIdRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/how': typeof SalesHowRoute
  '/sales/': typeof SalesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/bundle': typeof BundleRoute
  '/corporate': typeof CorporateRoute
  '/desk': typeof DeskRoute
  '/fees': typeof FeesRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/records': typeof RecordsRoute
  '/sell': typeof SellRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/you': typeof YouRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/pickup/$id': typeof PickupIdRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/how': typeof SalesHowRoute
  '/sales': typeof SalesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/bundle': typeof BundleRoute
  '/corporate': typeof CorporateRoute
  '/desk': typeof DeskRoute
  '/fees': typeof FeesRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/records': typeof RecordsRoute
  '/sell': typeof SellRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/you': typeof YouRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/new': typeof ListingsNewRoute
  '/pickup/$id': typeof PickupIdRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/how': typeof SalesHowRoute
  '/sales/': typeof SalesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/bundle'
    | '/corporate'
    | '/desk'
    | '/fees'
    | '/inbox'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/records'
    | '/sell'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/you'
    | '/listings/$id'
    | '/listings/new'
    | '/pickup/$id'
    | '/sales/$id'
    | '/sales/how'
    | '/sales/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/bundle'
    | '/corporate'
    | '/desk'
    | '/fees'
    | '/inbox'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/records'
    | '/sell'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/you'
    | '/listings/$id'
    | '/listings/new'
    | '/pickup/$id'
    | '/sales/$id'
    | '/sales/how'
    | '/sales'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/bundle'
    | '/corporate'
    | '/desk'
    | '/fees'
    | '/inbox'
    | '/login'
    | '/partners'
    | '/privacy'
    | '/records'
    | '/sell'
    | '/support'
    | '/terms'
    | '/welcome'
    | '/you'
    | '/listings/$id'
    | '/listings/new'
    | '/pickup/$id'
    | '/sales/$id'
    | '/sales/how'
    | '/sales/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  BundleRoute: typeof BundleRoute
  CorporateRoute: typeof CorporateRoute
  DeskRoute: typeof DeskRoute
  FeesRoute: typeof FeesRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  RecordsRoute: typeof RecordsRoute
  SellRoute: typeof SellRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  YouRoute: typeof YouRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsNewRoute: typeof ListingsNewRoute
  PickupIdRoute: typeof PickupIdRoute
  SalesIdRoute: typeof SalesIdRoute
  SalesHowRoute: typeof SalesHowRoute
  SalesIndexRoute: typeof SalesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundle': {
      id: '/bundle'
      path: '/bundle'
      fullPath: '/bundle'
      preLoaderRoute: typeof BundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees': {
      id: '/fees'
      path: '/fees'
      fullPath: '/fees'
      preLoaderRoute: typeof FeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/new': {
      id: '/listings/new'
      path: '/listings/new'
      fullPath: '/listings/new'
      preLoaderRoute: typeof ListingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup/$id': {
      id: '/pickup/$id'
      path: '/pickup/$id'
      fullPath: '/pickup/$id'
      preLoaderRoute: typeof PickupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/$id': {
      id: '/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof SalesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/how': {
      id: '/sales/how'
      path: '/sales/how'
      fullPath: '/sales/how'
      preLoaderRoute: typeof SalesHowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  BundleRoute: BundleRoute,
  CorporateRoute: CorporateRoute,
  DeskRoute: DeskRoute,
  FeesRoute: FeesRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  RecordsRoute: RecordsRoute,
  SellRoute: SellRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  YouRoute: YouRoute,
  ListingsIdRoute: ListingsIdRoute,
  ListingsNewRoute: ListingsNewRoute,
  PickupIdRoute: PickupIdRoute,
  SalesIdRoute: SalesIdRoute,
  SalesHowRoute: SalesHowRoute,
  SalesIndexRoute: SalesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
